apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elk-learning
  name: logs-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: logs-pv
