apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  labels:
    name: zookeeper-pvc
    pvname: zookeeper-pv
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem