apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk-learning
  name: empproducer
  labels:
    name: empproducer

spec:
  selector: 
    matchLabels:
      name: empproducer
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        name: empproducer
    spec:
      containers:
      - name: empproducer
        image: danishkyndryl/learningapis:empproducer
        ports:
          - containerPort: 10000
        imagePullPolicy: Never
        resources: 
          limits:
            memory: 1200Mi
            cpu: 400m
        livenessProbe: 
          httpGet:
            path: /empproducer/health
            port: 10000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe: 
          httpGet:
            path: /empproducer/health
            port: 10000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - mountPath: /SharedFolder/applicationlogs/
            name: logs-vol
        envFrom:
          - configMapRef:
              name: empproducer-config
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: logs-pvc