apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafkalogs-pv
  labels:
    name: kafkalogs-pv
  
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /SharedFolder/kafka/logs