apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: elk-learning
  name: logs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /SharedFolder/applicationlogs/
