apiVersion: v1
kind: Service
metadata:
  namespace: elk-learning
  name: mysql-service
  labels:
    name: mysql-service
spec:
  type: LoadBalancer
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306
