
name: Build And Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  buildAndPushToDockerHub:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        pwd
        cd Microservices/EmployeeManagementProducer/ && mvn -B package --file pom.xml

    - name: Docker Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: danishkyndryl/learningapis:empproducer

    - name: Build with Maven
      run: |
        pwd
        cd ../EmployeeManagementConsumer && mvn -B package --file pom.xml
    
    - name: Docker Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: danishkyndryl/learningapis:empconsumer
    
